// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AccidentsMockup.tsx": () => import("../components/mockups/AccidentsMockup.tsx"),
  "./components/mockups/DashboardMockup.tsx": () => import("../components/mockups/DashboardMockup.tsx"),
  "./components/mockups/EducationMockup.tsx": () => import("../components/mockups/EducationMockup.tsx"),
  "./components/mockups/InspectionsMockup.tsx": () => import("../components/mockups/InspectionsMockup.tsx"),
  "./components/mockups/MockupCanvas.tsx": () => import("../components/mockups/MockupCanvas.tsx"),
  "./components/mockups/NoticesMockup.tsx": () => import("../components/mockups/NoticesMockup.tsx")
};
